### ISSUE TITLE
A never-returning function must not return in ...

### ISSUE THREAD

**Issue by michaelw85** [Brain-WP/BrainMonkey#135]
Hi,

I'm using PHP 8.1 with:
- phpunit/phpunit 10.1.0
- brain/monkey 2.6.1
- pestphp/pest v2.5.0

When I write a simple test mocking WP's `get_option` all tests stop working. `error code 255`
`when('get_option')->justReturn(...)`

This results in a Fatal error:
PHP Fatal error:  A never-returning function must not return in [/Users/..../vendor/phpunit/phpunit/src/Framework/Constraint/Constraint.php on line 91](https://github.com/sebastianbergmann/phpunit/blob/main/src/Framework/Constraint/Constraint.php#L90)
When I change the typing from `never` to `void` what it used to be in PHPUnit 10.0.0 it works again.

I'm guessing there is a mismatch when the function is mocked but I haven't found the root cause yet.

**Comment by gmazzap** [comment]
Hi @michaelw85 I don't think this is an issue with Brain Monkey, this is a PHP 5.6 codebase, and we don't use return types at all. 

Maybe you could also look at Mockery, but I don't think there's anything we can do here to solve the issue.

Feel free to re-open if I'm wrong.

**Comment by michaelw85** [comment]
@gmazzap I think you are right, I haven't looked at Mockery or Patchwork yet. I think for some reason somewhere something is emitted in the mocked functions causing the `never` typing to fatal. 

This does mean the latest PHPUnit version + Brain Monkey is an issue unless you apply the patch I've provided.

**Comment by jrfnl** [comment]
> This does mean the latest PHPUnit version + Brain Monkey is an issue unless you apply the patch I've provided.

You mean PHPUnit 10 ? I know that Mockery definitely does not support PHPUnit 10 yet. Also see the open PRs in the repo, in particular this one: https://github.com/mockery/mockery/pull/1219

I'm not sure Patchwork would be problematic with PHPUnit 10 as it is a stand-alone tool which works independently of PHPUnit.

You might be jumping the gun a bit here.

**Comment by gmazzap** [comment]
Yep, before using BM with PHPUnit 10 we need Mockery to be compatible.

**Comment by michaelw85** [comment]
> > This does mean the latest PHPUnit version + Brain Monkey is an issue unless you apply the patch I've provided.
> 
> You mean PHPUnit 10 ? I know that Mockery definitely does not support PHPUnit 10 yet. Also see the open PRs in the repo, in particular this one: [mockery/mockery#1219](https://github.com/mockery/mockery/pull/1219)
> 
> I'm not sure Patchwork would be problematic with PHPUnit 10 as it is a stand-alone tool which works independently of PHPUnit.
> 
> You might be jumping the gun a bit here.

Yes, I'm running PHPUnit `10.1.1` which comes with the new Pest v2.
The issue you linked also mentions the `never` typing so without further investigation I'm going to assume Mockery is the issue. In my project, I just patched all `never` typings to `void` and it works fine so far.

**Comment by ghostwriter** [comment]
Hey folks,  

Mockery supports `never` return type for PHP 8.1 via https://github.com/mockery/mockery/pull/1184 & tagged [1.5.1](https://github.com/mockery/mockery/commits/1.5.1)

Updating `Brain-WP/BrainMonkey` composer to `^1.3.5 || ^1.4.4 || ^1.5.1` should resolve this.

Have a great day. ✌🏾

**Comment by jrfnl** [comment]
Thanks for pitching in @ghostwriter !

**Comment by paulshryock** [comment]
> Updating `Brain-WP/BrainMonkey` composer to `^1.3.5 || ^1.4.4 || ^1.5.1` should resolve this.

Is there anything blocking this? If it's just a matter of available time to handle the upgrade, I might have some time to pitch in and open a pull request.

**Comment by michaelw85** [comment]
> > Updating `Brain-WP/BrainMonkey` composer to `^1.3.5 || ^1.4.4 || ^1.5.1` should resolve this.
> 
> Is there anything blocking this? If it's just a matter of available time to handle the upgrade, I might have some time to pitch in and open a pull request.

For me the root cause still remains unresolved and to date I still don't know the exact origin of the issue. I dirty resolved it by locally patching all the return types. The issues were closed in the different repos because "blame" was given to another library or deemed a local issue in my codebase :(
